## YAML Template.
---
media_path: "videos"
video_name: "big_buck_bunny_480p_stereo.avi"
output_path: "output"
process_executor_server_url: "http://localhost:8000/"
fonts_path: "fonts"
font_default_name: "font.otf"
font_default_text_file: "test.txt"
report_file_name: "report"
performance_report_file_name: "perfomance_report"